install_helmfile: &install_helmfile
  name: Installing helmfile binary
  command: |
    wget https://github.com/roboll/helmfile/releases/download/v0.138.4/helmfile_linux_amd64 -O helmfile
    chmod +x helmfile
    sudo cp helmfile /usr/bin/
    helmfile --version

version: 2.1
jobs:
  deployment:
    docker:
      - image: circleci/python:2.7.14-stretch
    steps:
    - helm/install-helm-client:
        version: v3.4.2
    - run:
        command: helm version
    - run:
        <<: *install_helmfile

orbs:
  helm: circleci/helm@1.2.0

workflows:
  version: 2
  release:
    jobs:
      - deployment