install_helmfile: &install_helmfile
  name: Installing helmfile binary
  command: |
    wget https://github.com/roboll/helmfile/releases/download/v0.138.4/helmfile_linux_amd64 -O helmfile
    chmod +x helmfile
    sudo cp helmfile /usr/bin/
    helmfile --version

deployment_with_helmfile: &deployment
  name: Applying helmfile changes
  # command: IMAGE_TAG=${CIRCLE_BUILD_NUM} helmfile -e ${ENVIRONMENT} -f helm/teamup_all/helmfile.yaml apply
  command: IMAGE_TAG=latest_2 helmfile -e ${ENVIRONMENT} -f helm/teamup_all/helmfile.yaml apply

version: 2.1
jobs:
  deployment:
    docker:
      - image: circleci/python:2.7.14-stretch
    steps:
    - helm/install-helm-client:
        version: v3.4.2
    - run:
        command: helm version
    - run:
        <<: *install_helmfile
    - aws-cli/setup:
          profile-name: teamup-circleci
    - aws-eks/update-kubeconfig-with-authenticator:
        cluster-name: ${CLUSTER_NAME}
        install-kubectl: true
        aws-profile: teamup-circleci
    - run:
        <<: *deployment

orbs:
  helm: circleci/helm@1.2.0
  aws-cli: circleci/aws-cli@1.3.2
  aws-eks: circleci/aws-eks@1.0.3

workflows:
  version: 2
  release:
    jobs:
      - deployment:
          context: dev